# Generated by Django 3.2.15 on 2022-11-22 23:10

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, verbose_name='Телефон')),
                ('email', models.EmailField(db_index=True, max_length=100)),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('cost', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_orders', to='shop.client', verbose_name='клиент')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lvls', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1, verbose_name='уровни')),
                ('form', models.CharField(choices=[('CI', 'круг'), ('SQ', 'квадрат'), ('RE', 'прямоугольник')], max_length=2, verbose_name='форма')),
                ('topping', models.CharField(choices=[('NN', 'Без топпинга'), ('WS', 'Белый соус'), ('CA', 'Карамельный'), ('MA', 'Кленовый'), ('BI', 'Черничный'), ('MC', 'Молочный шоколад'), ('ST', 'Клубничный')], max_length=2, verbose_name='топпинг')),
                ('berries', models.CharField(choices=[('NN', 'Без ягод'), ('BK', 'Ежевика'), ('RA', 'Малина'), ('BL', 'Голубика'), ('ST', 'Клубника')], default='NN', max_length=2, verbose_name='ягоды')),
                ('decor', models.CharField(choices=[('NN', 'Без декора'), ('PS', 'Фисташки'), ('ME', 'Безе'), ('HA', 'Фундук'), ('PE', 'Пекан'), ('MR', 'Маршмеллоу'), ('MZ', 'Марципан')], default='NN', max_length=2, verbose_name='декор')),
                ('words', models.CharField(blank=True, max_length=50, null=True, verbose_name='надпись')),
                ('comment', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cake', to='shop.order', verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'торт',
                'verbose_name_plural': 'торты',
            },
        ),
    ]
