# Generated by Django 3.2.15 on 2022-11-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20221123_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='комментарий'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cake',
            name='words',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='надпись'),
            preserve_default=False,
        ),
    ]
