# Generated by Django 3.2.15 on 2022-11-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20221123_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cake',
            old_name='comment',
            new_name='comments',
        ),
        migrations.RemoveField(
            model_name='order',
            name='comment',
        ),
        migrations.AddField(
            model_name='order',
            name='delivcomments',
            field=models.TextField(blank=True, verbose_name='Комментарий курьеру'),
        ),
    ]
