# Generated by Django 3.2.15 on 2022-11-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20221124_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='topping',
            field=models.CharField(choices=[('1', 'Без'), ('2', 'Белый соус'), ('3', 'Карамельный'), ('4', 'Кленовый'), ('5', 'Черничный'), ('6', 'Молочный шоколад'), ('7', 'Клубничный')], max_length=2, verbose_name='топпинг'),
        ),
    ]
