# Generated by Django 3.2.15 on 2022-11-24 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_cake_topping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='berries',
            field=models.CharField(choices=[(1, 'нет'), (2, 'Ежевика'), (3, 'Малина'), (4, 'Голубика'), (5, 'Клубника')], default=('0', 'нет'), max_length=2, verbose_name='ягоды'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='decor',
            field=models.CharField(choices=[(1, 'нет'), (2, 'Фисташки'), (3, 'Безе'), (4, 'Фундук'), (5, 'Пекан'), (6, 'Маршмеллоу'), (7, 'Марципан')], default=('0', 'нет'), max_length=2, verbose_name='декор'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='form',
            field=models.CharField(choices=[(1, 'Круг'), (2, 'Квадрат'), (3, 'Прямоугольник')], max_length=2, verbose_name='форма'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='lvls',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3')], max_length=1, verbose_name='уровни'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='topping',
            field=models.CharField(choices=[(1, 'Без'), (2, 'Белый соус'), (3, 'Карамельный'), (4, 'Кленовый'), (5, 'Черничный'), (6, 'Молочный шоколад'), (7, 'Клубничный')], max_length=2, verbose_name='топпинг'),
        ),
    ]
