# Generated by Django 3.2.15 on 2022-11-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(0, 'Не оплачен'), (1, 'Оплачен'), (2, 'В доставке'), (3, 'Доставлен')], default=(0, 'Не оплачен'), max_length=20, verbose_name='Статус заказа'),
        ),
    ]
