# Generated by Django 3.2.15 on 2022-11-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_order_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='berries',
            field=models.IntegerField(choices=[(1, 'нет'), (2, 'Ежевика'), (3, 'Малина'), (4, 'Голубика'), (5, 'Клубника')], default=('0', 'нет'), verbose_name='ягоды'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='decor',
            field=models.IntegerField(choices=[(1, 'нет'), (2, 'Фисташки'), (3, 'Безе'), (4, 'Фундук'), (5, 'Пекан'), (6, 'Маршмеллоу'), (7, 'Марципан')], default=('0', 'нет'), verbose_name='декор'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='form',
            field=models.IntegerField(choices=[(1, 'Круг'), (2, 'Квадрат'), (3, 'Прямоугольник')], verbose_name='форма'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='lvls',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], verbose_name='уровни'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='topping',
            field=models.IntegerField(choices=[(1, 'Без'), (2, 'Белый соус'), (3, 'Карамельный'), (4, 'Кленовый'), (5, 'Черничный'), (6, 'Молочный шоколад'), (7, 'Клубничный')], verbose_name='топпинг'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Не оплачен'), (1, 'Оплачен'), (2, 'В доставке'), (3, 'Доставлен')], default=(0, 'Не оплачен'), verbose_name='Статус заказа'),
        ),
    ]
