# Generated by Django 3.2.15 on 2022-11-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20221127_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Не оплачен'), (1, 'Оплачен'), (2, 'В доставке'), (3, 'Доставлен')], default=0, verbose_name='Статус заказа'),
        ),
    ]
